### PR TITLE
Answer to Serial Box Coding Exercise

### PR DESCRIPTION
**Pull request by ptseng**
@kerryknight is tagged in the description of this PR.
Original Challenge: https://github.com/serialboxpub/sb-ios-coding-exercise

For separation of concerns and to lighten the weight of the view controller, I have refactored all networking logic into `Networking` and all persistence logic into `Storage`.

### Networking

Networking is a lightweight wrapper around `URLSession` where resources and responses can be defined by generic structs that conform to `Decodable`.  `JSONDecoder` is used to automagically parse json returned from the endpoint, thus saving us from the preexisting crude json parsing code, which satisfies **Task one.**

Loading of images within each cell was previously done by a synchronous call `Data(contentsOf: url)`.  According to Apple's documentation, this should not be used for network based usage as this is a synchronous operation that will block the main thread while the operation completes.  This has been factored out to use `URLSession.dataTask` which is asynchronous and non-blocking.  I have also implemented support for maintaining an in-memory cache for downloaded images and cancelling in-progress image downloads when the cell has scrolled offscreen before the download completes.  With a combination of the above changes, scrolling should now be smooth.  This satisfies **Task four.**

### Storage

Storage is a lightweight wrapper around `FileManager`, `JSONEncoder` and `JSONDecoder`.  This allows us to persist and save to disk a list of Recommendations, and retrieve them later to boost startup performance.  The application's cache directory is used for this purpose.  This satisfies **Task six.**

### TableView Automatic Resizing Cells

`taglineLabel` had a static intrinsic content size for height as defined by a layout height constraint with a constant value.  Therefore, no matter the size of the content of that label, it will always have a static height.  That layout height constraint was removed and the number of lines for that label was changed to zero.  All of the elements within the content view of the cell was checked to see that the top border anchor has a chain of constraints to the bottom border anchor.  The tableView delegate was given an estimated cell height of `UITableView.automaticDimension`.  This enabled the cells to be self sizing, dependent on the content length of `taglineLabel`.  This satisfies **Task two.**

I have checked the layout behavior on the old iPhone SE, iPhone 11, and iPad Pro 11 in both vertical and horizontal orientations and it displays properly without needed to adjust the font size of any UILabel.  This satisfies **Task three.**

### Recommendations Filtering

```
data.titles
.filter { $0.is_released == true }
.filter { !data.skipped.contains($0.title) }
.filter { !data.titles_owned.contains($0.title) }
.sorted { $0.rating ?? 0.0 > $1.rating ?? 0.0 }
.prefix(10)
```
Incoming recommendations are processed as above to create the top 10 list of recommendations.  Only allow recommendations that are released, for which the user has not skipped, and for which the user does not already own.  The result is then sorted by rating, descending, with null or no rating titles count as a zero rating.  Finally, only up to the first 10 results are included, the rest is trimmed.  This satisfies **Task five.**

## Conclusion

I hope I will be able to give a live defense of this answer.  If there are any questions as to whether I have satisfied the elements of this challenge, please do not hesitate to ask.

I have tried many code challenges from a lot of different companies.  This was one of my favorites.  Thank you, this was fun.

### CODE REVIEW

**Comment by ptseng** [comment]
Made grammatical changes to this PR’s comment.

**Comment by kerryknight** [comment]
Hi @ptseng, thanks so much for doing this.  Just FYI, I'm trying to get to these as fast as I can, so thanks for your patience.

**Comment by ptseng** [comment]
No worries, thanks!

**Comment by kerryknight** [comment]
Thanks for completing this!  I'm going to close the PR now.  Please expect to hear something from us by the middle of next week.

**Pull request closed without merging**
